// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/SomaTakata/ngin-link-server/internal/api/controller"
	"github.com/SomaTakata/ngin-link-server/internal/api/db"
	"github.com/SomaTakata/ngin-link-server/internal/api/repository"
	"github.com/SomaTakata/ngin-link-server/internal/api/router"
	"github.com/SomaTakata/ngin-link-server/internal/api/usecase"
	"github.com/SomaTakata/ngin-link-server/internal/api/util/clerkutil"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func Wire() *gin.Engine {
	gormDB := db.NewDB()
	userRepository := repository.NewUserRepository(gormDB)
	userUsecase := usecase.NewUserUsecase(userRepository)
	client := clerkutil.NewClerkClient()
	userController := controller.NewUserController(userUsecase, client)
	linkUsecase := usecase.NewLinkUsecase(userRepository)
	linkController := controller.NewLinkController(linkUsecase, client)
	engine := router.NewRouter(userController, linkController)
	return engine
}
