# fly.toml app configuration file generated for ngin-link-server on 2024-02-24T14:03:56+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ngin-link-server'
primary_region = 'nrt'

[build]
  [build.args]
    GO_VERSION = '1.22'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
